### ISSUE TITLE
AC became unavailable, unable to restore

### ISSUE THREAD

**Issue by adizag** [yonatanp/electrasmart-custom-component#13]
Hi

after wifi loss, AC became unavailable.
tried to remove the integration from configuration.yaml and restore but it didnt work.

**error in HA log:**
`Log Details (ERROR)
Logger: homeassistant.components.climate
Source: custom_components/electrasmart/climate.py:282
Integration: Climate (documentation, issues)
First occurred: 10:52:10 PM (1 occurrences)
Last logged: 10:52:10 PM

electrasmart: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 357, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/electrasmart/climate.py", line 288, in update
    self._renew_sid_if_needed()
  File "/config/custom_components/electrasmart/climate.py", line 282, in _renew_sid_if_needed
    self.ac.renew_sid()
  File "/usr/local/lib/python3.8/site-packages/electrasmart/client.py", line 113, in renew_sid
    self.sid = generate_sid(self.imei, self.token)
  File "/usr/local/lib/python3.8/site-packages/electrasmart/client.py", line 85, in generate_sid
    result = ElectraAPI.post(
  File "/usr/local/lib/python3.8/site-packages/electrasmart/client.py", line 49, in post
    assert j['data']['res'] == 0, "invalid res returned from command"
AssertionError: invalid res returned from command`

**Comment by GuyKh** [comment]
@adizag 
Refresh credential by running 
`electrasmart-auth` - to generate new imei and token.
Update it in HA and restart

**Comment by adizag** [comment]
That worked. tnx!
what could have made it change?

**Comment by GuyKh** [comment]
I think this issue is getting much worse when combined with #10

**Comment by yonatanp** [comment]
Chalking this one as part of the larger token block issue. Closing.
